QL_RapChieuPhim/Controllers/PhimsController.cs
using QL_RapChieuPhim.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QL_RapChieuPhim.Controllers
{
    public class PhimsController : Controller
    {
        QL_RapChieuPhimDataContext data = new QL_RapChieuPhimDataContext();

        public List<Phim> LayPhim(int count)
        {
            return data.Phims.OrderByDescending(a => a.TenPhim).Take(count).ToList();
        }
        // GET: Phims
        public ActionResult Index()
        {
            var phims = data.Phims.ToList();
            return View(phims);
        }
        public ActionResult Details(int id)
        {
            var phim = from p in data.Phims
                      where p.MaPhim == id
                      select p;
            return View(phim.Single());
        }
        public ActionResult LoaiPhim()
        {
            var loaiphim = from lp in data.TheLoais select lp;
            return PartialView(loaiphim);
        }

        public ActionResult SPTheoLoaiPhim(int id)
        {
            var phim = from ph in data.Phims where ph.MaTheLoai == id select ph;
            return View(phim.ToList());
        }
    }
}

QL_RapChieuPhim/Views/Phims/Details.cshtml
@model QL_RapChieuPhim.Models.Phim

@{
    ViewBag.Title = "Chi Tiết Phim";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<div class="details-page">
    <div class="img-container">
        <img src="~/Images/@Model.HinhAnh" alt="@Model.TenPhim" />
    </div>
    <div class="details-container">
        <h4>@Model.TenPhim</h4>
        <p>Thời lượng: <span class="highlight">@Model.ThoiLuong phút</span></p>
        <p><span class="bold">Tóm tắt: </span>@Model.TomTat</p>
        <div id="DatVe">
            <!-- Liên kết đến hành động ShowTimes với tham số MaPhim -->
            <a href="@Url.Action("ShowTimes", "DatVe", new { id = Model.MaPhim })" class="btn btn-primary">
                Xem Suất Chiếu
            </a>
        </div>
    </div>
</div>

QL_RapChieuPhim/Views/Phims/Index.cshtml
@model IEnumerable<QL_RapChieuPhim.Models.Phim>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<div class="card-container">
    @foreach (var phim in Model)
    {
        <div class="card">
            <img src="~/Images/@phim.HinhAnh" class="card-img-top" alt="@phim.TenPhim" />
            <div class="card-body">
                <h5 class="card-title">@phim.TenPhim</h5>
                <p class="card-text">@phim.TomTat</p>
            </div>
            <div class="row card-footer">
                <div class="col-6">
                    <a href="@Url.Action("Details", "Phims", new { id = phim.MaPhim })" class="btn btn-primary">Xem chi tiết</a>
                </div>
                <div class="col-6 text-end">
                    <p>@phim.ThoiLuong phút</p>
                </div>
            </div>
        </div>
    }
</div>

QL_RapChieuPhim/Views/Phims/LoaiPhim.cshtml
<!-- LoaiPhim.cshtml -->
@model IEnumerable<QL_RapChieuPhim.Models.TheLoai>

@foreach (var loai in Model)
{
    <li class="nav-item">
        <a class="nav-link" href="@Url.Action("SPTheoLoaiPhim", "Phims", new { id = loai.MaTheLoai })">@loai.TenTheLoai</a>
    </li>
}

QL_RapChieuPhim/Views/Phims/SPTheoLoaiPhim.cshtml
@model IEnumerable<QL_RapChieuPhim.Models.Phim>

@{
    ViewBag.Title = "SPTheoLoaiPhim";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}
<h3 style="text-align: center; color: red;">PHIM THEO LOẠI</h3>
<div class="card-container">
    @foreach (var phim in Model)
    {
        <div class="card">
            <img src="~/Images/@phim.HinhAnh" class="card-img-top" alt="@phim.TenPhim" />
            <div class="card-body">
                <h5 class="card-title">@phim.TenPhim</h5>
                <p class="card-text">@phim.TomTat</p>
                <div class="row">
                    <div class="col-6">
                        <a href="@Url.Action("Details", "Phims", new { id = phim.MaPhim })" class="btn btn-primary">Xem chi tiết</a>
                    </div>
                    <div class="col-6 text-end">
                        <p>@phim.ThoiLuong phút</p>
                    </div>
                </div>
            </div>
        </div>
    }
</div>